# Generated by Django 6.1 on 2026-09-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitor",
            name="body",
            field=models.TextField(blank=True, default="", max_length=8192),
        ),
    ]
