// Generated by scripts/generate-types.mjs — do not edit by hand.

export interface paths {
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Clears the refresh-token cookie. There is no server-side token blacklist (see the access/refresh token design), so an access token already handed out stays valid until it expires on its own — this only stops it from being silently renewed on this browser. */
        post: operations["auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auth_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Returns only the access token in the body. The refresh token is set as an httpOnly cookie (see Set-Cookie), never exposed to page JavaScript. */
        post: operations["auth_token_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description No request body — the refresh token is read from the httpOnly cookie set by POST /auth/token, not from JSON. Rotation is always on, so a successful call also re-sets that cookie with a new refresh token. */
        post: operations["auth_token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["incidents_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["incidents_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{id}/acknowledge/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Acknowledge an incident
         * @description Marks an OPEN incident as ACKNOWLEDGED — a human has seen it and is aware, without claiming it's fixed. Only valid from OPEN; acknowledging an already-ACKNOWLEDGED or RESOLVED incident returns 409. Resolving still only ever happens automatically, from the monitor recovering.
         */
        post: operations["incidents_acknowledge_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/monitors/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["monitors_list"];
        put?: never;
        post: operations["monitors_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/monitors/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["monitors_retrieve"];
        put: operations["monitors_update"];
        post?: never;
        delete: operations["monitors_destroy"];
        options?: never;
        head?: never;
        patch: operations["monitors_partial_update"];
        trace?: never;
    };
    "/api/v1/monitors/{id}/check/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Queue an immediate check outside the regular schedule
         * @description Always asynchronous — the request returns 202 as soon as the check is queued, never waiting on the probe itself, since the target could be slow or unreachable. Poll poll_url (the same paginated check history endpoint) to see the result once it lands. Rate limited to 5/min per user: this endpoint lets a caller make our infrastructure send a request to an arbitrary URL, so it's deliberately tighter than the general per-user rate.
         */
        post: operations["monitors_check_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/monitors/{id}/checks/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["monitors_checks_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/monitors/{id}/pause/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["monitors_pause_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/monitors/{id}/resume/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["monitors_resume_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/monitors/{id}/stats/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Uptime and response-time summary over a period
         * @description Built entirely from pre-aggregated MonitorHourlyStat rows, never from raw CheckResult history — cheap regardless of how far back `period` reaches. `series` is bucketed by hour for period=24h and by day for 7d/30d. p95_response_time_ms is a weighted average of each hour's own p95, not a true period-wide percentile — a documented approximation, not a bug.
         */
        get: operations["monitors_stats_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notification-channels/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["notification_channels_list"];
        put?: never;
        post: operations["notification_channels_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notification-channels/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["notification_channels_retrieve"];
        put: operations["notification_channels_update"];
        post?: never;
        delete: operations["notification_channels_destroy"];
        options?: never;
        head?: never;
        patch: operations["notification_channels_partial_update"];
        trace?: never;
    };
    "/api/v1/notification-channels/{id}/verify/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a real test notification through this channel
         * @description Synchronous — the caller waits for the actual send attempt, unlike every other notification, which is delivered later via the outbox. On success, sets is_verified=true; only verified channels ever receive real incident notifications. On failure, the channel is returned with is_verified unchanged and last_error/last_error_at set.
         */
        post: operations["notification_channels_verify_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description The real response shape of both /auth/token and /auth/token/refresh —
         *     used only for schema generation (@extend_schema in views.py), never
         *     instantiated to build an actual response. Documents that `refresh`
         *     deliberately isn't here; it goes out as an httpOnly cookie instead of
         *     in this body, so a naive schema built from SimpleJWT's own serializers
         *     (which do include `refresh`) would document a field that never
         *     actually appears.
         */
        AccessToken: {
            readonly access: string;
        };
        CheckResult: {
            readonly id: number;
            /** Format: date-time */
            readonly checked_at: string;
            readonly success: boolean;
            readonly status_code: number | null;
            readonly response_time_ms: number | null;
            readonly error_type: (components["schemas"]["ErrorTypeEnum"] | components["schemas"]["NullEnum"]) | null;
            readonly error_message: string | null;
            readonly response_size_bytes: number | null;
        };
        /**
         * @description Schema-only — documents what CheckResultCursorPagination actually
         *     returns (apps.common.pagination), not instantiated at runtime.
         *
         *     Exists because the checks history view builds its paginator by hand
         *     instead of going through the ViewSet's normal pagination_class wiring
         *     (see apps/monitors/views.py for why), which means drf-spectacular has
         *     no way to detect on its own that this response is paginated at all,
         *     let alone paginated with a cursor instead of a page number — left to
         *     its own inference it wrongly assumes the ViewSet's default
         *     page-number pagination, complete with a `count` field this endpoint
         *     never actually returns.
         */
        CheckResultCursorPage: {
            next: string | null;
            previous: string | null;
            results: components["schemas"]["CheckResult"][];
        };
        /**
         * @description * `ok` - ok
         *     * `error` - error
         * @enum {string}
         */
        DependencyStatusEnum: "ok" | "error";
        /**
         * @description * `DNS_ERROR` - DNS error
         *     * `CONNECTION_REFUSED` - Connection refused
         *     * `CONNECTION_ERROR` - Connection error
         *     * `TIMEOUT` - Timeout
         *     * `SSL_ERROR` - SSL error
         *     * `TOO_MANY_REDIRECTS` - Too many redirects
         *     * `RESPONSE_TOO_LARGE` - Response too large
         *     * `UNEXPECTED_STATUS` - Unexpected status
         *     * `BLOCKED_TARGET` - Blocked target
         *     * `INTERNAL_ERROR` - Internal error
         * @enum {string}
         */
        ErrorTypeEnum: "DNS_ERROR" | "CONNECTION_REFUSED" | "CONNECTION_ERROR" | "TIMEOUT" | "SSL_ERROR" | "TOO_MANY_REDIRECTS" | "RESPONSE_TOO_LARGE" | "UNEXPECTED_STATUS" | "BLOCKED_TARGET" | "INTERNAL_ERROR";
        HealthCheck: {
            status: components["schemas"]["HealthCheckStatusEnum"];
            database: components["schemas"]["DependencyStatusEnum"];
            redis: components["schemas"]["DependencyStatusEnum"];
            version: string;
        };
        /**
         * @description * `ok` - ok
         *     * `degraded` - degraded
         * @enum {string}
         */
        HealthCheckStatusEnum: "ok" | "degraded";
        /**
         * @description Shape of the 202 response from triggering an out-of-schedule check —
         *     there's no object to represent, just an acknowledgement and where to
         *     look for the result once it exists.
         */
        ImmediateCheckAccepted: {
            readonly detail: string;
            readonly poll_url: string;
        };
        IncidentDetail: {
            /** Format: uuid */
            readonly id: string;
            readonly monitor: components["schemas"]["_MonitorSummary"];
            readonly status: components["schemas"]["IncidentStatusEnum"];
            /** Format: date-time */
            readonly started_at: string;
            /** Format: date-time */
            readonly acknowledged_at: string | null;
            /** Format: date-time */
            readonly resolved_at: string | null;
            readonly duration_seconds: number | null;
            readonly trigger_error_type: (components["schemas"]["TriggerErrorTypeEnum"] | components["schemas"]["NullEnum"]) | null;
            readonly trigger_status_code: number | null;
            readonly failed_checks_count: number;
            readonly resolution_source: (components["schemas"]["ResolutionSourceEnum"] | components["schemas"]["NullEnum"]) | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        IncidentList: {
            /** Format: uuid */
            readonly id: string;
            readonly monitor: components["schemas"]["_MonitorSummary"];
            readonly status: components["schemas"]["IncidentStatusEnum"];
            /** Format: date-time */
            readonly started_at: string;
            /** Format: date-time */
            readonly acknowledged_at: string | null;
            /** Format: date-time */
            readonly resolved_at: string | null;
            readonly duration_seconds: number | null;
            readonly trigger_error_type: (components["schemas"]["TriggerErrorTypeEnum"] | components["schemas"]["NullEnum"]) | null;
            readonly trigger_status_code: number | null;
            readonly failed_checks_count: number;
        };
        /**
         * @description * `OPEN` - Open
         *     * `ACKNOWLEDGED` - Acknowledged
         *     * `RESOLVED` - Resolved
         * @enum {string}
         */
        IncidentStatusEnum: "OPEN" | "ACKNOWLEDGED" | "RESOLVED";
        /**
         * @description * `60` - 60
         *     * `120` - 120
         *     * `300` - 300
         *     * `600` - 600
         *     * `900` - 900
         *     * `1800` - 1800
         *     * `3600` - 3600
         * @enum {integer}
         */
        IntervalSecondsEnum: 60 | 120 | 300 | 600 | 900 | 1800 | 3600;
        Me: {
            /** Format: uuid */
            readonly id: string;
            /** Format: email */
            readonly email: string;
            readonly monitor_quota: number;
            readonly monitors_used: number;
            /** Format: date-time */
            readonly created_at: string;
        };
        /**
         * @description * `GET` - GET
         *     * `HEAD` - HEAD
         *     * `POST` - POST
         * @enum {string}
         */
        MethodEnum: "GET" | "HEAD" | "POST";
        MonitorDetail: {
            /** Format: uuid */
            readonly id: string;
            readonly name: string;
            /** Format: uri */
            readonly url: string;
            readonly method: components["schemas"]["MethodEnum"];
            readonly expected_status: number;
            readonly interval_seconds: components["schemas"]["IntervalSecondsEnum"];
            readonly timeout_seconds: number;
            readonly headers: unknown;
            readonly failure_threshold: number;
            readonly success_threshold: number;
            readonly is_enabled: boolean;
            readonly status: string;
            readonly consecutive_failures: number;
            readonly consecutive_successes: number;
            /** Format: date-time */
            readonly last_checked_at: string | null;
            readonly last_response_time_ms: number | null;
            /** Format: uuid */
            readonly open_incident_id: string | null;
            /** Format: double */
            readonly uptime_24h: number | null;
            readonly avg_response_time_24h_ms: number | null;
            readonly notification_channels: components["schemas"]["_NotificationChannelSummary"][];
            /** Format: date-time */
            readonly next_check_at: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        MonitorList: {
            /** Format: uuid */
            readonly id: string;
            readonly name: string;
            /** Format: uri */
            readonly url: string;
            readonly method: components["schemas"]["MethodEnum"];
            readonly expected_status: number;
            readonly interval_seconds: components["schemas"]["IntervalSecondsEnum"];
            readonly timeout_seconds: number;
            readonly is_enabled: boolean;
            readonly status: string;
            /** Format: date-time */
            readonly last_checked_at: string | null;
            readonly last_response_time_ms: number | null;
            /** Format: uuid */
            readonly open_incident_id: string | null;
            /** Format: date-time */
            readonly next_check_at: string;
            /** Format: date-time */
            readonly created_at: string;
        };
        MonitorStats: {
            /** Format: uuid */
            monitor_id: string;
            period: string;
            /** Format: date-time */
            period_from: string;
            /** Format: date-time */
            period_to: string;
            summary: components["schemas"]["PeriodSummary"];
            series: components["schemas"]["StatsSeriesBucket"][];
        };
        /**
         * @description The small body returned by /pause and /resume —
         *     deliberately not the full detail representation, since those actions
         *     only ever change `is_enabled` and whatever falls out of it.
         */
        MonitorStatus: {
            /** Format: uuid */
            readonly id: string;
            readonly status: string;
            readonly is_enabled: boolean;
        };
        /**
         * @description Input-only: create/update go through apps.monitors.services, never
         *     `serializer.save()` — see the ViewSet. This class's own `.create()`/
         *     `.update()` are therefore never called; it exists purely to validate
         *     and to shape `validated_data` into service kwargs.
         *
         *     `name`/`url` end up required because the model gives them no default;
         *     everything else is optional here because the model field already has
         *     one (DRF's ModelSerializer derives `required` from that automatically).
         */
        MonitorWrite: {
            name: string;
            /** Format: uri */
            url: string;
            method?: components["schemas"]["MethodEnum"];
            expected_status?: number;
            interval_seconds?: components["schemas"]["IntervalSecondsEnum"];
            timeout_seconds?: number;
            headers?: unknown;
            failure_threshold?: number;
            success_threshold?: number;
        };
        /**
         * @description Input-only: create/update go through apps.monitors.services, never
         *     `serializer.save()` — see the ViewSet. This class's own `.create()`/
         *     `.update()` are therefore never called; it exists purely to validate
         *     and to shape `validated_data` into service kwargs.
         *
         *     `name`/`url` end up required because the model gives them no default;
         *     everything else is optional here because the model field already has
         *     one (DRF's ModelSerializer derives `required` from that automatically).
         */
        MonitorWriteRequest: {
            name: string;
            /** Format: uri */
            url: string;
            method?: components["schemas"]["MethodEnum"];
            expected_status?: number;
            interval_seconds?: components["schemas"]["IntervalSecondsEnum"];
            timeout_seconds?: number;
            headers?: unknown;
            failure_threshold?: number;
            success_threshold?: number;
            notification_channel_ids?: string[];
        };
        NotificationChannel: {
            /** Format: uuid */
            readonly id: string;
            type: components["schemas"]["TypeEnum"];
            name: string;
            config?: unknown;
            readonly is_verified: boolean;
            is_active?: boolean;
            readonly last_error: string | null;
            /** Format: date-time */
            readonly last_error_at: string | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        NotificationChannelRequest: {
            type: components["schemas"]["TypeEnum"];
            name: string;
            config?: unknown;
            is_active?: boolean;
        };
        /** @enum {unknown} */
        NullEnum: null;
        PaginatedIncidentListList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["IncidentList"][];
        };
        PaginatedMonitorListList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["MonitorList"][];
        };
        PaginatedNotificationChannelList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["NotificationChannel"][];
        };
        /**
         * @description Input-only: create/update go through apps.monitors.services, never
         *     `serializer.save()` — see the ViewSet. This class's own `.create()`/
         *     `.update()` are therefore never called; it exists purely to validate
         *     and to shape `validated_data` into service kwargs.
         *
         *     `name`/`url` end up required because the model gives them no default;
         *     everything else is optional here because the model field already has
         *     one (DRF's ModelSerializer derives `required` from that automatically).
         */
        PatchedMonitorWriteRequest: {
            name?: string;
            /** Format: uri */
            url?: string;
            method?: components["schemas"]["MethodEnum"];
            expected_status?: number;
            interval_seconds?: components["schemas"]["IntervalSecondsEnum"];
            timeout_seconds?: number;
            headers?: unknown;
            failure_threshold?: number;
            success_threshold?: number;
            notification_channel_ids?: string[];
        };
        PatchedNotificationChannelRequest: {
            type?: components["schemas"]["TypeEnum"];
            name?: string;
            config?: unknown;
            is_active?: boolean;
        };
        /**
         * @description Mirrors apps.checks.stats.PeriodSummary — schema-only, the view
         *     builds the actual response from that dataclass directly rather than
         *     instantiating this serializer at runtime.
         */
        PeriodSummary: {
            /** Format: double */
            uptime_ratio: number | null;
            checks_total: number;
            checks_failed: number;
            avg_response_time_ms: number | null;
            p95_response_time_ms: number | null;
            incidents_count: number;
            total_downtime_seconds: number;
        };
        Register: {
            /** Format: email */
            email: string;
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            password_confirm: string;
        };
        /**
         * @description * `AUTO_RECOVERY` - Auto recovery
         *     * `SYSTEM_RECONCILE` - System reconcile
         * @enum {string}
         */
        ResolutionSourceEnum: "AUTO_RECOVERY" | "SYSTEM_RECONCILE";
        StatsSeriesBucket: {
            bucket: string;
            checks_total: number;
            checks_failed: number;
            avg_response_time_ms: number | null;
            p95_response_time_ms: number | null;
        };
        TokenObtainPairRequest: {
            email: string;
            password: string;
        };
        /**
         * @description * `BLOCKED_TARGET` - BLOCKED_TARGET
         *     * `CONNECTION_ERROR` - CONNECTION_ERROR
         *     * `CONNECTION_REFUSED` - CONNECTION_REFUSED
         *     * `DNS_ERROR` - DNS_ERROR
         *     * `INTERNAL_ERROR` - INTERNAL_ERROR
         *     * `RESPONSE_TOO_LARGE` - RESPONSE_TOO_LARGE
         *     * `SSL_ERROR` - SSL_ERROR
         *     * `TIMEOUT` - TIMEOUT
         *     * `TOO_MANY_REDIRECTS` - TOO_MANY_REDIRECTS
         *     * `UNEXPECTED_STATUS` - UNEXPECTED_STATUS
         * @enum {string}
         */
        TriggerErrorTypeEnum: "BLOCKED_TARGET" | "CONNECTION_ERROR" | "CONNECTION_REFUSED" | "DNS_ERROR" | "INTERNAL_ERROR" | "RESPONSE_TOO_LARGE" | "SSL_ERROR" | "TIMEOUT" | "TOO_MANY_REDIRECTS" | "UNEXPECTED_STATUS";
        /**
         * @description * `EMAIL` - Email
         *     * `TELEGRAM` - Telegram
         * @enum {string}
         */
        TypeEnum: "EMAIL" | "TELEGRAM";
        /**
         * @description Just enough of a Monitor to identify it from inside an incident —
         *     the full monitor is one request away via its own id.
         *
         *     `method` is here because a monitor's name is not unique: the same URL
         *     checked by GET and by POST is two monitors that can legitimately share
         *     a name, and without the method an incident feed lists both under a
         *     label that can't tell them apart.
         */
        _MonitorSummary: {
            /** Format: uuid */
            readonly id: string;
            readonly name: string;
            /** Format: uri */
            readonly url: string;
            readonly method: components["schemas"]["MethodEnum"];
        };
        /**
         * @description Just enough of a channel to identify it from inside a monitor — the
         *     full channel (config, verification state) is one request away.
         */
        _NotificationChannelSummary: {
            /** Format: uuid */
            readonly id: string;
            readonly type: components["schemas"]["TypeEnum"];
            readonly name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    auth_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["RegisterRequest"];
                "multipart/form-data": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Register"];
                };
            };
        };
    };
    auth_token_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenObtainPairRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenObtainPairRequest"];
                "multipart/form-data": components["schemas"]["TokenObtainPairRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessToken"];
                };
            };
        };
    };
    auth_token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessToken"];
                };
            };
        };
    };
    incidents_list: {
        parameters: {
            query?: {
                monitor?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /**
                 * @description * `OPEN` - Open
                 *     * `ACKNOWLEDGED` - Acknowledged
                 *     * `RESOLVED` - Resolved
                 */
                status?: "ACKNOWLEDGED" | "OPEN" | "RESOLVED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedIncidentListList"];
                };
            };
        };
    };
    incidents_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this incident. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentDetail"];
                };
            };
        };
    };
    incidents_acknowledge_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this incident. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentDetail"];
                };
            };
        };
    };
    monitors_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedMonitorListList"];
                };
            };
        };
    };
    monitors_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MonitorWriteRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["MonitorWriteRequest"];
                "multipart/form-data": components["schemas"]["MonitorWriteRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitorDetail"];
                };
            };
        };
    };
    monitors_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this monitor. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitorDetail"];
                };
            };
        };
    };
    monitors_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this monitor. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MonitorWriteRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["MonitorWriteRequest"];
                "multipart/form-data": components["schemas"]["MonitorWriteRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitorDetail"];
                };
            };
        };
    };
    monitors_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this monitor. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    monitors_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this monitor. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedMonitorWriteRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedMonitorWriteRequest"];
                "multipart/form-data": components["schemas"]["PatchedMonitorWriteRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitorWrite"];
                };
            };
        };
    };
    monitors_check_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this monitor. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImmediateCheckAccepted"];
                };
            };
        };
    };
    monitors_checks_retrieve: {
        parameters: {
            query?: {
                /** @description Opaque pagination cursor from a previous response's next/previous. */
                cursor?: string;
                /** @description Filter by error type. */
                error_type?: string;
                page_size?: number;
                /** @description Only checks at or after this time. */
                since?: string;
                /** @description Filter by outcome. */
                success?: boolean;
                /** @description Only checks before this time. */
                until?: string;
            };
            header?: never;
            path: {
                /** @description A UUID string identifying this monitor. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckResultCursorPage"];
                };
            };
        };
    };
    monitors_pause_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this monitor. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitorStatus"];
                };
            };
        };
    };
    monitors_resume_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this monitor. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitorStatus"];
                };
            };
        };
    };
    monitors_stats_retrieve: {
        parameters: {
            query?: {
                /** @description How far back to summarize. */
                period?: "24h" | "30d" | "7d";
            };
            header?: never;
            path: {
                /** @description A UUID string identifying this monitor. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitorStats"];
                };
            };
        };
    };
    notification_channels_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedNotificationChannelList"];
                };
            };
        };
    };
    notification_channels_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationChannelRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["NotificationChannelRequest"];
                "multipart/form-data": components["schemas"]["NotificationChannelRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationChannel"];
                };
            };
        };
    };
    notification_channels_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this notification channel. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationChannel"];
                };
            };
        };
    };
    notification_channels_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this notification channel. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationChannelRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["NotificationChannelRequest"];
                "multipart/form-data": components["schemas"]["NotificationChannelRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationChannel"];
                };
            };
        };
    };
    notification_channels_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this notification channel. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    notification_channels_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this notification channel. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedNotificationChannelRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedNotificationChannelRequest"];
                "multipart/form-data": components["schemas"]["PatchedNotificationChannelRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationChannel"];
                };
            };
        };
    };
    notification_channels_verify_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this notification channel. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationChannel"];
                };
            };
        };
    };
    health_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthCheck"];
                };
            };
        };
    };
}
