# Generated by Django 6.1 on 2026-08-23 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("monitors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("checked_at", models.DateTimeField()),
                ("success", models.BooleanField()),
                ("status_code", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("response_time_ms", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "error_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DNS_ERROR", "DNS error"),
                            ("CONNECTION_REFUSED", "Connection refused"),
                            ("CONNECTION_ERROR", "Connection error"),
                            ("TIMEOUT", "Timeout"),
                            ("SSL_ERROR", "SSL error"),
                            ("TOO_MANY_REDIRECTS", "Too many redirects"),
                            ("RESPONSE_TOO_LARGE", "Response too large"),
                            ("UNEXPECTED_STATUS", "Unexpected status"),
                            ("BLOCKED_TARGET", "Blocked target"),
                            ("INTERNAL_ERROR", "Internal error"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("error_message", models.CharField(blank=True, max_length=500, null=True)),
                ("response_size_bytes", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "monitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_results",
                        to="monitors.monitor",
                    ),
                ),
            ],
            options={
                "ordering": ["-checked_at"],
                "indexes": [
                    models.Index(
                        fields=["monitor", "-checked_at"], name="checkresult_monitor_idx"
                    ),
                    models.Index(fields=["checked_at"], name="checkresult_checked_at_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("error_type__isnull", True), ("success", True)),
                            models.Q(("error_type__isnull", False), ("success", False)),
                            _connector="OR",
                        ),
                        name="checkresult_success_matches_error_type",
                    )
                ],
            },
        ),
    ]
