# Generated by Django 6.1 on 2026-08-24 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checks", "0001_initial"),
        ("monitors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonitorHourlyStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("hour_start", models.DateTimeField()),
                ("checks_total", models.PositiveIntegerField()),
                ("checks_failed", models.PositiveIntegerField()),
                ("avg_response_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("min_response_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("max_response_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("p95_response_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("downtime_seconds", models.PositiveIntegerField(default=0)),
                (
                    "monitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hourly_stats",
                        to="monitors.monitor",
                    ),
                ),
            ],
            options={
                "ordering": ["-hour_start"],
                "indexes": [
                    models.Index(fields=["monitor", "-hour_start"], name="hourlystat_monitor_idx"),
                    models.Index(fields=["hour_start"], name="hourlystat_hour_start_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("monitor", "hour_start"), name="hourlystat_unique_hour"
                    )
                ],
            },
        ),
    ]
