#!/usr/bin/env node
// Regenerates src/api/schema.ts from the backend's OpenAPI schema.
//
// Usage:
//   node scripts/generate-types.mjs                        # fetch from a running backend
//   node scripts/generate-types.mjs path/to/schema.yaml     # from a file (used in CI)
//
// The generated file is committed to the repo — it's the frontend's
// compile-time contract with the API, and every other file in src/api
// imports types from it. CI regenerates it from a fresh schema and diffs
// against the committed version to catch drift, rather than trusting
// whoever last touched a serializer to have remembered to re-run this.

import { fileURLToPath, pathToFileURL } from 'node:url'
import { dirname, resolve } from 'node:path'
import openapiTS, { astToString } from 'openapi-typescript'
import { writeFile } from 'node:fs/promises'

const __dirname = dirname(fileURLToPath(import.meta.url))
const OUTPUT_PATH = resolve(__dirname, '../src/api/schema.ts')
const DEFAULT_SCHEMA_URL = 'http://localhost:8000/api/schema/'

const source = process.argv[2] ?? DEFAULT_SCHEMA_URL
console.log(`Generating types from ${source} -> ${OUTPUT_PATH}`)

// A local file path has to become a file:// URL — a bare string is treated
// as raw schema content to parse, not a path to read from disk.
const schemaLocation = source.startsWith('http')
  ? new URL(source)
  : pathToFileURL(resolve(process.cwd(), source))

const ast = await openapiTS(schemaLocation)
const header = '// Generated by scripts/generate-types.mjs — do not edit by hand.\n\n'
await writeFile(OUTPUT_PATH, header + astToString(ast))

console.log('Done.')
