# Generated by Django 6.1 on 2026-08-24 16:25

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("monitors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("RESOLVED", "Resolved"),
                        ],
                        default="OPEN",
                        max_length=12,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "trigger_error_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BLOCKED_TARGET", "BLOCKED_TARGET"),
                            ("CONNECTION_ERROR", "CONNECTION_ERROR"),
                            ("CONNECTION_REFUSED", "CONNECTION_REFUSED"),
                            ("DNS_ERROR", "DNS_ERROR"),
                            ("INTERNAL_ERROR", "INTERNAL_ERROR"),
                            ("RESPONSE_TOO_LARGE", "RESPONSE_TOO_LARGE"),
                            ("SSL_ERROR", "SSL_ERROR"),
                            ("TIMEOUT", "TIMEOUT"),
                            ("TOO_MANY_REDIRECTS", "TOO_MANY_REDIRECTS"),
                            ("UNEXPECTED_STATUS", "UNEXPECTED_STATUS"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("trigger_status_code", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("failed_checks_count", models.PositiveIntegerField(default=0)),
                (
                    "resolution_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AUTO_RECOVERY", "Auto recovery"),
                            ("SYSTEM_RECONCILE", "System reconcile"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "monitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidents",
                        to="monitors.monitor",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["monitor", "-started_at"], name="incident_monitor_started_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "RESOLVED"), _negated=True),
                        fields=("monitor",),
                        name="incident_one_open_per_monitor",
                    )
                ],
            },
        ),
    ]
