# Generated by Django 6.1 on 2026-09-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_telegramclaim"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationchannel",
            name="config",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
